### ISSUE TITLE
Investigation: Add GitHub login

### ISSUE THREAD

**Issue by te4-adrian-almetun-smeds** [itggot-TE4/Fire-experts#10]
## Acceptance criteria
- [ ] Investigate how to implement a login system using GitHub authentication
- [ ] Open a issue with a solution proposal

## Information
https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps
https://docs.github.com/en/free-pro-team@latest/rest/guides/basics-of-authentication

**Comment by itggot-linus-styren** [comment]
Bra att ni jobbar med investigations där det är oklart hur mycket jobb en task innebär. Kallas även för spikes: https://www.scaledagileframework.com/spikes/

En liten notering på era issues är att ni kanske menar "Acceptence Criteria" istället för "Solution proposal" i ovanstående checklista?

Skillnaden är helt enkelt att ni skriver vad slutresultatet förväntas vara i "Acceptance criteria" och ifall ni vill specifiera "hur" så kan ni skriva det i "Solution proposal".

**Comment by te4-adrian-almetun-smeds** [comment]
Closed by #77
